### ISSUE TITLE
Switch from elastic search implementation to open search

### ISSUE THREAD

**Issue by tylerbarna** [nasa-gcn/architect-plugin-search#16]
standing issue from weekly meeting seems to be open search local deployment not having support for MacOS. 

Potential solution proposed was a docker image

**Comment by tylerbarna** [comment]
@lpsinger I don't believe I have permissions to assign issues to people

**Comment by lpsinger** [comment]
OpenSearch has an issue about  building macOS binaries, but it has been open for a long time: https://github.com/opensearch-project/OpenSearch/issues/1449

**Comment by ronitagarwala01** [comment]
I've added a local installation of Opensearch. However, like you all said, it won't work on Mac.

**Comment by lpsinger** [comment]
@ronitagarwala01, that's alright. If you provide a PR to switch to OpenSearch, then @tylerbarna and I can work on porting it to macOS.
